# 生产环境下最好将 NODE_ENV 设置为 production , 该项设置必须放在第一位
NODE_ENV: 'development'
SERVER_NAME: 'personal server'
# start 以下两项 的设置在 NODE_ENV 不为 development 时将失效，该设计意在为非开发模式下服务器提升性能，生产环境下跟踪日志和开发日志是没必要的
TRACE_LOG_LEVEL: 'trace'
DEV_LOG_LEVEL: 'trace'
# end
AUDIT_LOG_LEVEL: 'trace'
JWT_APP_NAME: 'nodejs-server'
JWT_APP_ID: 'appid'
JWT_APP_SECERT: 'appsecert'
# service
REDIS_URL: 'redis://localhost:6379'
MONGO_URL: 'mongodb://localhost:3001/meteor'
ROOT_URL: 'http://loaclhost:3000'
