# 生产环境下最好将 NODE_ENV 设置为 production , 该项设置必须放在第一位
NODE_ENV: 'development'
SERVER_NAME: 'personal server'


# start 以下两项 的设置在 NODE_ENV 为 production 时将失效，该设计意在为非开发模式下服务器提升性能，生产环境下跟踪日志和开发日志是没必要的
TRACE_LOG_LEVEL: 'trace'
DEV_LOG_LEVEL: 'trace'
# end

AUDIT_LOG_LEVEL: 'trace'
JWT_APP_NAME: 'my project'
JWT_APP_ID: 'jwtAppId'
JWT_APP_SECERT: 'jwtSecret'


# service 以下项项目启动后修改无效
REDIS_URL: 'redis://192.168.1.167:6379'
MONGO_URL: 'mongodb://localhost:27017/test'
