export const errorType = {
    URL_NOT_FOUND: 'URL_NOT_FOUND',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    BAD_REQUEST: 'BAD_REQUEST',
    FORBIDDEN: 'FORBIDDEN',
    NOT_FOUND: 'NOT_FOUND',
    SUCCESS: 'SUCCESS',
    TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
    INVALID_ARGUMENTS: 'INVALID_ARGUMENTS',
    BE_LOGOUT: 'BE_LOGOUT'
};

export const errorCodeMap = {
    '200': ['SUCCESS'],
    '400': ['INVALID_', 'BAD_REQUEST', 'INVALID_ARGUMENTS'],
    '401': ['UNAUTHORIZED', 'BE_LOGOUT'],
    '403': ['FORBIDDEN'],
    '404': ['NOT_FOUND', 'URL_NOT_FOUND'],
    '408': ['REQUEST_TIMEOUT'],
    '429': ['TOO_MANY_REQUESTS'],
    '500': ['INTERNAL_SERVER_ERROR']
};
